### ISSUE TITLE
How do I get the alt checker updated?

### ISSUE THREAD

**Issue by ghost** [TheMrGong/MCLeaksApiClient#10]
I'm currently testing the anti-vpn plugin with the MCLeaks alt "Stay_Young" on my server. Using the api directly in my browser and the anti-vpn plugin, the alt does not show up as an mcleaks alt. How would I fix this? Thanks!

**Comment by TheMrGong** [comment]
The bot that scraped MCLeaks accounts has stopped functioning I'm afraid. Currently there is no method for users to add accounts to the database as there isn't a way to verify the account is MCLeaks. I'll try to work on a replacement for the bot as soon as I can.

**Comment by ghost** [comment]
Oof, is the problem the recaptcha? If so, I see what the problem is. If not, have you considered faking the authenticator app after getting the token?

Edit: This looks promising. I don't know for sure if it works though. [https://www.maketecheasier.com/bypass-google-recaptcha-images/](https://www.maketecheasier.com/bypass-google-recaptcha-images/)

**Comment by TheMrGong** [comment]
No, it's changes within the website that I need to account for as the reCAPTCHA problem was already solved.

**Comment by egg82** [comment]
Hi, I (likely) created/run the aforementioned Anti-VPN plugin.

In preparation for its upcoming 6.0.0 release, I was wondering if there's anything I can do to help get this project back up and running? The database is still mildly useful as-is, but not having recent accounts added does make it more difficult for server owners to make use of the project.

If there's anything I can do, please let me know!

**Comment by TheMrGong** [comment]
Hello, the original issue was that MCLeaks seemed to be transitioning to a different service (named easymc); however, that no longer seems to be the case, and MCLeaks works again. As such, the bot is fully functional again and adding new accounts.
