### ISSUE TITLE
Can't Connect?

### ISSUE THREAD

**Issue by Vexentric** [TheMrGong/MCLeaksApiClient#3]
Whenever trying to detect an account, it doesn't detect it as an mcleaks account. There are no errors. I tried to connect to the api url in my browser but that doesnt't work. (https://gyazo.com/2c5f1904c0da9c0b347b0a08afd0db7b)

**Comment by TheMrGong** [comment]
Ah crap, forgot to pay for the domain. Ill get it fixed ASAP

**Comment by TheMrGong** [comment]
Domain has been paid, sorry for the troubles.

**Comment by Vexentric** [comment]
Still getting timed out when connecting using a browser and the api isn't detecting accounts ;-;

**Comment by TheMrGong** [comment]
Should be fixed, might have been trying to use it while I was updating the API. Try again.

**Comment by Vexentric** [comment]
It kinda works; detected 2/5 of the accounts i tested with.

EDIT: Nvm it works fine again, thanks so much :)

EDIT 2: Still seem to be able to get a few through. May I ask how/where you check the names from?

EDIT 3: So I did a little more testing and figure out that if it doesn't work instantly, it will work after a minute or 2. Is there a time limit inbetween requests?

**Comment by TheMrGong** [comment]
Sorry for the late response. The way the accounts are gotten is through a bot that auto grabs mcleaks accounts. I've had this running for a while, just only recently made it public. 

The best reason I can come up with for the bad connection is not using the best REST server software. I plan on migrating to a better solution tommorow, as it's already late for me. In short, no, there isn't a limit between requests, just the server can't keep up. Sorry for any troubles.

**Comment by TheMrGong** [comment]
Try out the latest version, 1.5-SNAPSHOT, tell me if it works better. The server backend has been upgraded also.

**Comment by Vexentric** [comment]
Alright I will check it out, thank you so much! Also, if you need a better host for your bot/restful api, I can provide one for free, just message me (if I can figure out how ;P)
