### ISSUE TITLE
Database Name

### ISSUE THREAD

**Issue by Guichaguri** [TheMrGong/MCLeaksApiClient#4]
I received a suggestion to support your database in my [mod/plugin](https://github.com/Guichaguri/BOHA).

How should I call your database? "MrGong's Database"?

Thanks :)

**Comment by TheMrGong** [comment]
I'm in the same boat as you regarding naming. If I had to choose, I'd probably go with "Gong's Database" although if you come up with a better name I'm open arms. Thank you for supporting my database!

**Comment by Guichaguri** [comment]
I'll be using "Gong's Database". If you find another name, just give me a heads up :)

I have just released a new version supporting your database, thanks for creating and maintaining it
